export const IPC_CHANNELS = {
  chooseProjectFolder: 'workspace:choose-project-folder',
  getWorkspaceState: 'workspace:get-state',
  selectProject: 'workspace:select-project',
  createTab: 'workspace:create-tab',
  closeTab: 'workspace:close-tab',
  renameTab: 'workspace:rename-tab',
  setActiveTab: 'workspace:set-active-tab',
  createSubtab: 'workspace:create-subtab',
  closeSubtab: 'workspace:close-subtab',
  renameSubtab: 'workspace:rename-subtab',
  setActiveSubtab: 'workspace:set-active-subtab',
  terminalStart: 'terminal:start',
  terminalInput: 'terminal:input',
  terminalResize: 'terminal:resize',
  terminalKill: 'terminal:kill',
  terminalData: 'terminal:data',
  terminalExit: 'terminal:exit',
  authStartLogin: 'auth:start-login',
  authLogout: 'auth:logout',
  authRefreshStatus: 'auth:refresh-status',
  authSetViewBounds: 'auth:set-view-bounds',
  authHideView: 'auth:hide-view',
  profileRefreshUsage: 'profile:refresh-usage',
  profileImportDefault: 'profile:import-default',
  profileGenerateCliWrapper: 'profile:generate-cli-wrapper',
  workspaceStateChanged: 'workspace:state-changed',
} as const;

export type IpcChannel = (typeof IPC_CHANNELS)[keyof typeof IPC_CHANNELS];
